analyzer:
  errors:
    eol_at_end_of_file: ignore
    lines_longer_than_80_chars: ignore
    require_trailing_commas: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false